name: Build Game
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build and Package with jlink
        run: |
          ./gradlew jlink --no-daemon --stacktrace \
            -Dorg.gradle.console=plain \
            -Dorg.gradle.parallel=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.os }}
          path: build/image